scripts/scripts.js
Fix #43 
Test: https://resilient-getmetadatajson--blog--adobe.hlx3.page/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers?delayed=off
=> fix: add resilience to getMetadataJson

helix-query.yaml, helix-sitemap.yaml
=> feat(sitemap): add sitemap

scripts/scripts.js, tools/sidekick/config.js
Fix #45 
https://issue-45--blog--adobe.hlx3.page/
=> feat(sidekick): custom plugins

blocks/video/video.js
Fix #39 
Test urls:
- https://fix-video-loading--blog--adobe.hlx3.page/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers?delayed=off
- https://fix-video-loading--blog--adobe.hlx3.page/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers
=> fix: video not preloaded

blocks/footer/footer.js, blocks/gnav/gnav.js, scripts/scripts.js
Fix #59 
Test page:
- https://adjust-links--blog--adobe.hlx3.page/?delayed=off
- https://adjust-links--blog--adobe.hlx3.page/
=> fix: adjust links on non-prod env

blocks/gnav/gnav.css, styles/styles.css
* Updated Gnav Promo to better match spec
* Updated Gnav mobile sub menus to better match spec
* Updated Gnav sub menus to better match medium spec
* Update search field on mobile to align with new top level items
* Fix search highlight color
Resolves: GH-55
https://gnav-polish--blog--adobe.hlx3.page/?helix-env=stage
=> GH-55 - Gnav Polish

blocks/gnav/gnav-search.js
display first tag as category in gnav search result cards
#62 
https://gnav-search-card-category--blog--adobe.hlx3.page/
https://gnav-search-card-category--blog--adobe.hlx3.page/?delayed=off
=> fix: display first tag as category in search

scripts/delayed.js
Fix #25 
@mokimo I saw you are made some changes to theblog analytics. I brought your changes over. It would be great if you could review this PR. It seems to be doing the same thing that for theblog.
Test page: https://analytics--blog--adobe.hlx3.page/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers
=> feat: import and adjust analytics code

blocks/gnav/gnav.css
https://gnav-search-tweaks--blog--adobe.hlx3.page/
see before and after below...
=> chore: gnav search result tweaks

.circleci/config.yml, monitoring/content-check.js, monitoring/health-check.js
New monitoring automation setup, migrated from https://github.com/adobe/theblog-tests
=> chore: monitoring automation

scripts/scripts.js
https://trim-title--blog--adobe.hlx3.page/
adds better trim
=> fix: more specific trim

tools/hero-image-test/index.html
https://hero-image-tester--blog--adobe.hlx3.page/tools/hero-image-test/index.html
=> chore: port image tester

helix-query.yaml
=> fix: use h1 for title

scripts/delayed.js
https://get-social--blog--adobe.hlx3.page/en/publish/2021/11/08/tech-empowers-fashion
vs. 
https://main--blog--adobe.hlx3.page/en/publish/2021/11/08/tech-empowers-fashion
=> chore: readd get social

blocks/image-50-image-50/image-50-image-50.css
Fix #90 
Test page (check most of the images):
- https://main--blog--adobe.hlx3.page/en/publish/2021/10/08/a-bit-of-madness-doorstep-market-creates-an-award-winning-global-market-for-local-makers (before)
- https://image-50--blog--adobe.hlx3.page/en/publish/2021/10/08/a-bit-of-madness-doorstep-market-creates-an-award-winning-global-market-for-local-makers (after)
=> feat: image 50 block

blocks/banner/banner.js, scripts/scripts.js
Open https://main--blog--adobe.hlx3.page/en/publish/2021/04/01/36-days-of-type-2021
2 issues:
- a Javascript error
- the banner is not loaded (because URL ends with .html)
Test page: https://code-resilience--blog--adobe.hlx3.page/en/publish/2021/04/01/36-days-of-type-2021
=> fix: code resilience

tools/sidekick/config.js, tools/sidekick/msal-browser-2.14.2.js, tools/sidekick/sharepoint.js
Fix #98 
https://issue-98--blog--adobe.hlx3.page/
=> feat(sidekick): update feed

head.html
Fix #103 
Test URL: https://fix-social-media--blog--adobe.hlx3.page/jp/publish/2021/10/26/cc-new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers
Cannot be tested via the Twitter validator because it says the page is block by robots.txt...
=> fix: add required meta

sitemap-index.xml
replaced https with http in namespace (Google Search Console will otherwise complain)
=> fix: add all language sitemaps

blocks/article-feed/article-feed.css, blocks/article-feed/article-feed.js
Display localized "no results found" text in article feed when no results are found 
Spinner is added for long filter times
#74 
- no results: https://article-feed-no-results--blog--adobe.hlx3.page/br/topics/news
- filter for products robohelp or coldfusion: https://article-feed-no-results--blog--adobe.hlx3.page/en/topics/customer-stories
=> fix: display text when no articles found in feed

scripts/delayed.js
A small analytics bug was introduced during the migration for the `pageFilterInfo` field from [theblog](https://github.com/adobe/theblog/blob/master/scripts/martech.js#L131-L138)
- [Jira Issue](https://jira.corp.adobe.com/browse/MWPW-97131)
- [Analytics specification](https://wiki.corp.adobe.com/display/marketingtech/Blogs.adobe.com+-+DataLayer+Specification)
We've been notified that this field has been changed & want to fix this.
Tested on the outer cdn
old) https://main--blog--adobe.hlx.live/en/publish/2021/11/23/adobe-mlb-partner-next-gen-fan-experiences
new) https://analytics-fix--blog--adobe.hlx.live/en/publish/2021/11/23/adobe-mlb-partner-next-gen-fan-experiences
Top, `pageFilterInfo` after the fix
Bottom, `pageFilterInfo` before the fix
=> fix: correct pageFilterInfo analytics

scripts/scripts.js
Adding a missing bracket to `function decoratePictures(main)`.
=> add missing bracket to decoratePictures selector

404.html
add header, footer on 404 page
https://404-page--blog--adobe.hlx3.page/404.html
=> fix: add header, footer

blocks/tags/tags.js
see https://cq-dev.slack.com/archives/CT7LDKK0F/p1639520856457300?thread_ts=1639497124.436200&cid=CT7LDKK0F
=> fix(tags): use tag name instead of tag URL as `target` for RUM instrumentation

scripts/scripts.js
Fix #135 
- https://issue-135--blog--adobe.hlx3.page/de/
=> fix(regression): add index to publish dependencies

scripts/delayed.js, scripts/scripts.js
transition to new cmp outlined in 2020 CMP Engineering Implementation
https://new-cmp--blog--adobe.hlx3.page/?helix-env=dev
=> fix: transition to new cmp

scripts/scripts.js
- https://trieloff-patch-1--blog--adobe.hlx3.page/?rum=on
=> chore(rum): increase sampling rate

scripts/scripts.js
remove site title from blog metadata
concerns: this will very likely need to be updated to be localized, awaiting confirmation
https://temp-feat-title-fix--blog--adobe.hlx.live/
=> temp fix: remove site title from card

scripts/scripts.js
URL for testing:
- https://rum-errors-in-errors--blog--adobe.hlx3.page/?rum=on
=> fix(rum): guard against missing element in source finder

scripts/scripts.js
- https://rum-hostname--blog--adobe.hlx3.page/?cwv=on
=> refactor(rum): use rum.hlx.page instead of rum.hlx3.page

blocks/banner/banner.js
optimized inline image in banner block based on browser's ability 
fixes #161
https://optimize-banner-img--blog--adobe.hlx.live/en/publish/2022/03/23/future-facing-learning-for-student-success-a-creative-campus-collaboration-recap
https://optimize-banner-img--blog--adobe.hlx.live/en/publish/2022/03/23/artist-lynne-hardys-illustrations-honor-her-familys-navajo-past-present-and-future
=> fix: optimize banner image

styles/lazy-styles.css, styles/styles.css
1. Set font display back to swap.
2. Add size adjust so Trebuchet MS better matches Adobe Clean
Resolves: MWPW-107929
URLs to Test:
- https://swap-fonts--blog--adobe.hlx.live/
- https://blog.adobe.com/
=> MWPW-107929 - Swap font loading

blocks/embed/embed.js
https://tiktok-video-fix--blog--adobe.hlx3.page/en/publish/2022/04/13/express-your-fandom-tips-social-content-share-worthy
=> Fix the race condition of tiktok embed js

styles/styles.css
* Allow embed links to break
Resolves: MWPW-108414
=> MWPW-108414 - Links push page bounds

scripts/scripts.js
=> Removing GTM

blocks/carousel/carousel.css, blocks/carousel/carousel.js
- Refactored the carousel block JavaScript to be less repetitive
- Added keyboard functionality (left/right arrows to change slide, 'exit' to close the lightbox.)
- Added the ability to have a caption for each slide in the carousel block
- The caption is bold and italic, with a gradient background, and may have a hyperlink which you can click on to go to another page...
Test URLs:
- Before: https://main--blog--adobe.hlx.page/en/drafts/solene/carousel
- After: https://captions-in-carousel--blog--webistry-development.hlx.page/en/drafts/solene/carousel
=> Carousel block: Added ability to have a caption for each slide.

head.html, scripts/scripts.js
* Removed use-credentials in head
* Non-blocking call to milo blocks list
* Ability to safely override if not on prod (libstore=my-cool-feature)
* Libstore also supports local dev
* Libstore uses blog.adobe.com/libs on prod
* Block loader and LCP should be minimally impacted
Resolves: MWPW-109893
Test URLs:
- Before: https://main--blog--adobe.hlx.page/en/publish/2021/12/13/introducing-creative-cloud-express
- After: https://libs-support--blog--adobe.hlx.page/en/publish/2021/12/13/introducing-creative-cloud-express
=> MWPW-109893 - Onboard Blog to Milo Libs

blocks/interlinks/interlinks.js
* Increase limit to 8000
Resolves: MWPW-110370
=> MWPW-110370 - Increase interlink count

tools/sidekick/config.json
See https://github.com/adobe/helix-sidekick-extension/pull/113
=> chore(sidekick): adjust to latest schema

blocks/personalized-articles/personalized-articles.css, blocks/personalized-articles/personalized-articles.js, scripts/scripts.js
this PR contains a feature that uses the past few articles and their tags as an indication of the areas that user might be interested in and fills a `personalized-articles` block with recommendations...
https://personalized-articles--blog--adobe.hlx.page/en/drafts/uncleds/personalized
https://personalized-articles--blog--adobe.hlx.page/en/drafts/uncleds/news-for-you
=> feat: personalized articles

styles/lazy-styles.css
Added purple styling to links standard, hover, and focus state to video container blocks and divs afterwards.
https://jira.corp.adobe.com/browse/MWPW-116981
Resolves the issue above.
Tested locally using these links:
Before:  https://main--blog--adobe.hlx.page/en/drafts/jennie/creating-waves-with-creativity-for-ocean-conservation
After: https://link-style-update--blog--adobe.hlx.page/en/drafts/jennie/creating-waves-with-creativity-for-ocean-conservation
=> Link styling update after video blocks

.circleci/config.yml
=> fix: newrelic monitor url

blocks/walls-io/walls-io.css, blocks/walls-io/walls-io.js
This is a first version implementation of the Walls.io block requested by Matt's team. If you have any comments or questions please reach out to me on slack to discuss the block!
You can find a demo of the block here:
https://wallsio--blog--webistry-development.hlx.page/en/drafts/williambsm/wallsio-v2
You can find the document here:
https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc=%7B2BFA9C9A-1061-4A50-BECF-C5C5FC7CD2B4%7D&file=wallsio-v2.docx&action=default&mobileredirect=true
All values are whitelisted in order to avoid insecure injections.
=> New block request - Walls.io block

blocks/footer/footer.js
- adds an empty alt attribute to the decorative icon
Test URL: https://alt-in-globe-img--blog--adobe.hlx.live/
=> MWPW-118279 - Globe icon in "Change language" button is missing empty alt

blocks/section-metadata/section-metadata.js, blocks/tabs/tabs.css, blocks/tabs/tabs.js
Importing the tabs block from Milo keeping the same approach as I did for the section-metadata block.
I did have to make some class adjustments in order to make sure the style stuck.
Authoring page:
https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc=%7B20542FCC-3BC7-4B95-8A6D-59F0F8C1E530%7D&file=tabs.docx&action=default&mobileredirect=true
Before URL:
https://main--blog--webistry-development.hlx.page/en/drafts/williambsm/tabs
After URL:
https://milo-tabs--blog--webistry-development.hlx.page/en/drafts/williambsm/tabs
=> Import the tabs blog from Milo

blocks/sticky-header/sticky-header.css, blocks/sticky-header/sticky-header.js, icons/newsletter-icon.svg
=> sticky-header

scripts/scripts.js
Test URL:
- https://trieloff-patch-1--blog--adobe.hlx.live/?rum=on
=> fix(rum): re-enable lazy, viewmedia, and viewblock checkpoints

404.html
try https://rum-404--blog--adobe.hlx.page/missing?rum=on
=> feat(rum): instrument 404s
