adobe/blog

scripts/scripts.js

Fix #56 
The problem was that we removed the parent elements too eagerly.
- Before: https://main--blog--adobe.hlx3.page/en/publish/2021/04/22/photoshop-and-adobe-experience-manager-accelerating-creativity-through-apis
- After: https://issue-56--blog--adobe.hlx3.page/en/publish/2021/04/22/photoshop-and-adobe-experience-manager-accelerating-creativity-through-apis

fix(images): js error if side-by-side

---

scripts/scripts.js

Fix #56 
The test page has both a real images block with 2 images in it, and 2 imagesnext to eachother in the default content.
Before:
- https://main--blog--adobe.hlx3.page/en/drafts/rofe/test
- https://issue-56--blog--adobe.hlx3.page/en/drafts/rofe/test

feat(images): auto side-by-side images block

---

blocks/article-feed/article-feed.js
blocks/gnav/gnav-search.js
scripts/delayed.js
scripts/scripts.js

fix:
https://github.com/adobe/blog/issues/38
initial support for chunked index... 
compare:
https://chunked-index--blog--adobe.hlx.live/
https://chunked-index--blog--adobe.hlx.live/en/topics/creativity
vs. 
https://main--blog--adobe.hlx.live/
https://main--blog--adobe.hlx.live/en/topics/creativity
with chunk size set at `500` i am getting the following on throttled
```
throttled: chunk measurements - loading: 2437ms filtering: 39ms
unthrottled: chunk measurements - loading: 147ms filtering: 14ms
```
having said that, the inner loop for the filtering is considerably more expensive, which is definitely a problem especially with respect to the blocking time over 50ms. as in the current index architecture this loop has to run through up to 13k items, i think we should consider optimizing the …

feat: chunked index

---

scripts/scripts.js

https://trim-title--blog--adobe.hlx3.page/
vs. 
https://main--blog--adobe.hlx3.page/

fix: remove appended Adobe

---

blocks/recommended-articles/recommended-articles.css

Depending on how the page is loading, `styles.css` may come after `recommended-articles` and take over. Articles are then not visible.
Test pages:
- https://main--blog--adobe.hlx3.page/en/drafts/jennie/breaking-into-the-professional-creative-industry
- https://fix-invisible-recommended-article--blog--adobe.hlx3.page/en/drafts/jennie/breaking-into-the-professional-creative-industry
Other pages still work as before https://fix-invisible-recommended-article--blog--adobe.hlx3.page/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers

fix: css selectors must be stronger than main style ones

---

scripts/scripts.js

If a recommended has no tags, the code crashes.
Test page: 
- https://fix-not-tag-crash--blog--adobe.hlx3.page/

fix: article without tags crash the taxonomy

---

blocks/recommended-articles/recommended-articles.css

https://recommnded-articles-block--blog--adobe.hlx3.page/
vs. 
https://main--blog--adobe.hlx3.page/

chore: better unhiding

---

scripts/scripts.js

Some tags are filtered out, mainly because they are not trimmed.

feat: improve tag list by triming and filtering

---

scripts/scripts.js

fix #105 
Works for both Chrome and Safari: https://fix-invalid-date--blog--adobe.hlx3.page

fix: replace '-' with '/'

---

blocks/gnav/gnav.js
scripts/scripts.js

Client id is wrong and locale was hardcoded to `en_US`.
I have tested all the locales, they take me to the corresponding login page on adobe.com.
Test: https://fix-gnav-setup--blog--adobe.hlx3.page/

fix: gnav config and locale

---

blocks/social-links/social-links.css
blocks/social-links/social-links.js

- add email support in social links block
- add language specific proceeding text
before: https://main--blog--adobe.hlx3.page/en/authors/lucinda-parish
after: https://social-links--blog--adobe.hlx3.page/en/authors/lucinda-parish

fix: email support in social + language specific text

---

helix-query.yaml

Removed duplicate 'description' key in index properties.

Remove duplicate 'description' key from helix-query

---

scripts/scripts.js

Port adobe/business-website#134.
#107 
https://cache-placeholders--blog--adobe.hlx3.page/
https://cache-placeholders--blog--adobe.hlx3.page/?lighthouse=on

fix: store placeholders in window obj to reduce repeat calls

---

monitoring/content-check.js

We can add more sophisticated content checks back once the `$browser` instance in the scripted monitor script is a more modern version of chrome that can handle blog.adobe.com...
- https://rofe-patch-1--blog--adobe.hlx3.page/

chore: limit content check to static marker

---

blocks/embed/embed.js
scripts/scripts.js

fix bug in the `buildFigure` function that would omit captions and links when `picture`, `video`, or `a` elements were not wrapped in `p` tag
#99 
- before: https://blog.adobe.com/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers
- after: https://build-figure--blog--adobe.hlx3.page/en/publish/2021/10/26/new-creative-cloud-releases-enable-creative-collaboration-drive-innovation-empower-creative-careers
- before: https://blog.adobe.com/jp/publish/2021/10/15/cc-stock-collection-review02
- after: https://build-figure--blog--adobe.hlx3.page/jp/publish/2021/10/15/cc-stock-collection-review02

fix: build figure and caption functionality

---

scripts/scripts.js

This PR adds the ability to track individual media and block impressions using RUM data. It introduces a new 
`target` property in the RUM payload that is either the image URL or the block name, and it gets fired in
combination with the `viewmedia` and `viewblock` checkpoints that get triggered when either DOM element is at
least 25% visible in the viewport.
With this PR we will be able to get authors and developers feedback on which compontents and images get seen
most frequently, although a corresponding change in `helix-rum-collector` is needed to allow the `target` property.
Test URLs: 
- https://rumio--blog--adobe.hlx3.page/en/publish/2021/10/26/max-2021-photography-releases?rum=on#gs.gxlcl6
- https://rumio--blog--adobe.hlx3.page/?rum=on
Scroll around in the page and inspect the …

Intersection Observer Support for RUM

---

.circleci/config.yml

https://rofe-patch-1--blog--adobe.hlx3.page/

chore: switch to new outer CDN

---

scripts/scripts.js

https://main--blog--adobe.hlx.live/en/publish/2021/11/23/adobe-mlb-partner-next-gen-fan-experiences#gs.gwj35t
vs. 
https://show-redirected-cards--blog--adobe.hlx.live/en/publish/2021/11/23/adobe-mlb-partner-next-gen-fan-experiences#gs.gwj35t

chore: show redirected cards in recommended articles

---

scripts/scripts.js

Some related articles have a redirect in place and fetch will throw CORS errors. The change will handle the use-case and stop execution (ignore the errors).
https://fix-related-fetch--blog--adobe.hlx3.page/
Code should not have unhandled errors.
Locally

fix: handle fetch errors in getMetadataJson

---

scripts/scripts.js

Temporary substitution of the french topic title 'transformation digitale' to 'transformation numérique' (display only).
Before: https://main--blog--adobe.hlx3.page/fr/publish/2021/11/17/volvo-cars-modernise-ses-services-grace-a-adobe-sign
After: https://topic-subs--blog--adobe.hlx3.page/fr/publish/2021/11/17/volvo-cars-modernise-ses-services-grace-a-adobe-sign

feat: add temp title substitutes

---

blocks/tags/tags.js
scripts/scripts.js

extracts a CSS selector for the element that has been clicked and shares it as the RUM events `target` value, as requested by @davidnuescheler in yesterday's show & tell.
Test URL: https://rum-click-interceptor--blog--adobe.hlx.live/?rum=on

feat(rum): add `target` attribute to click event tracking

---

blocks/embed/embed.css

unobserved embeds display the link before the embed iframe is created, resulting in righthand side whitespace on blog posts with embeds before the embeds are viewed
propose hide and break the embed links to prevent whitespace 
https://unobserved-embeds--blog--adobe.hlx3.page/en/publish/2021/12/13/introducing-creative-cloud-express

fix: hide unobserved embed block links

---

blocks/embed/embed.js

allow for different type of slideshare link (circumvent slideshare fetch)
https://slideshare-embed--blog--adobe.hlx3.page/en/publish/2021/07/23/announcing-2021-sundance-ignite-x-adobe-fellows

fix: embed different type of slideshare url

---

blocks/footer/footer.js

* add `tabindex` to "Change language" button
* add `aria-label` to "Change language" button
* add `Enter` and `Space` event listeners to "Change language" button
* add `aria-current=page` to currently selected "Change language" option
#131 
https://region-picker-accessibility--blog--adobe.hlx.live/

fix: add accessibility features to region picker

---

scripts/scripts.js

The Privacy script was loaded twice:
* at load - https://github.com/adobe/blog/blob/main/scripts/scripts.js#L1304
* after some time via lazyload - https://github.com/adobe/blog/blob/main/scripts/scripts.js#L1363
https://privacy-issue--blog--adobe.hlx3.page/
locally

fix: load privacy once

---

blocks/article-header/article-header.css
blocks/article-header/article-header.js

- reinstate invalid date highlight in preview (when metadata publication date does not match date in pathname)
invalid date: https://highlight-incorrect-date--blog--adobe.hlx3.page/en/drafts/katie/publish/2022/02/02/adobe-one-of-worlds-most-admired-companies
valid date: https://main--blog--adobe.hlx3.page/en/drafts/katie/publish/2022/02/02/how-young-chae-embraces-new-obstacles-as-an-opportunity-to-learn-and-grow

feat: highlight invalid dates in preview

---

blocks/embed/embed.js

Fix #149 
https://main--blog--adobe.hlx3.page/en/publish/2021/08/17/behind-the-success-of-the-pinkfong-baby-shark-phenomenon
vs
https://vimeo-video--blog--adobe.hlx3.page/en/publish/2021/08/17/behind-the-success-of-the-pinkfong-baby-shark-phenomenon
Check the first video, it should be loaded.

fix: vimeo embed - use player url if provided

---

tools/sidekick/config.js

Move custom plugins to tools dropdown to free up space.
Related to https://github.com/adobe/helix-sidekick/issues/263
https://sk-tools--blog--adobe.hlx3.page/?martech=off

chore: move custom buttons to tools menu

---

scripts/delayed.js

No clue how we have not seen that before!
Test: 
https://blog.adobe.com/en/publish/2022/03/08/adobe-named-one-of-worlds-most-innovative-companies-in-ai-by-fast-company
vs
https://fix-external-links--blog--adobe.hlx3.page/en/publish/2022/03/08/adobe-named-one-of-worlds-most-innovative-companies-in-ai-by-fast-company

fix: js error on most of the pages when checking external links

---

blocks/footer/footer.js
blocks/gnav/gnav.js
scripts/scripts.js

Port https://github.com/adobe/helix-project-boilerplate/pull/70
I have also included the removal of the `.html`.
This could potentially break a lot...
Test - (Stephan Hawthorne link at the top + all links...):
https://blog.adobe.com/en/publish/2020/10/08/adobe-photography-releases-october-2020
vs
https://make-links-relative--blog--adobe.hlx3.page/en/publish/2020/10/08/adobe-photography-releases-october-2020

feat: make links relative

---

blocks/gnav/gnav.css
blocks/newsletter-modal/newsletter-modal.css

Simple visual fixed for height: 100% being prioritised over media query.
There is also a fix for the CTA button showing too small on Safari.
https://newsletter_modal_hotfix--blog--webistry-development.hlx3.page/

fix(newsletter-modal): Fixing height on desktop

---

blocks/carousel/carousel.js

Quick fix for the Javascript error that sometimes happens in the carousel block (`cannot read .tagName of null`)
Test URLs:
- Before: https://main--blog--adobe.hlx.page/en/drafts/solene/carousel
- After: https://fix-js-error--blog--webistry-development.hlx.page/en/drafts/solene/carousel

Fix Javascript error

---

blocks/toolkit/toolkit.css

Description:
A fix to prevent images from going full height on Safari IOS.
Test URL:
https://toolkit-safari-hotfix--blog--webistry-development.hlx3.page/en/publish/2022/05/18/create-change-create-waves

fix(toolkit): safari mobile hotfix

---

styles/lazy-styles.css

Patch fix to ensure links below carousel are blue as expected. 
Before: https://main--blog--adobe.hlx.page/en/drafts/solene/carousel
After: https://carousel-link-fix--blog--adobe.hlx.page/en/drafts/solene/carousel

Added link color rules for after carousel

---

scripts/scripts.js

The sidekick can be loaded "too early", so we should check if it's already there before attaching the listener.
https://sk-mv3--blog--adobe.hlx.live/

fix: load plugins if sidekick is already there

---

scripts/scripts.js

move privacy outside of the LCP critical path
https://main--blog--adobe.hlx.live/en/publish/2022/10/17/the-creative-event-of-year-here-register-free-adobe-max-2022
vs.
https://privacy-lcp--blog--adobe.hlx.live/en/publish/2022/10/17/the-creative-event-of-year-here-register-free-adobe-max-2022
the LCP values may be a bit misleading because of the impact of `main--milo--` origin, but i think the delta should stay the same, compared to blog.adobe.com.
meaning that there should be a positive LCP impact of about `500ms`

chore: move privacy script post LCP

---

blocks/section-metadata/section-metadata.css
blocks/section-metadata/section-metadata.js

I’ve manually imported the “section-metadata” block in a way that accounts for all the DOM/class changes between Milo and Blog. You can preview the experience here in this cool little draft I've created:
Before:
https://main--blog--webistry-development.hlx.page/en/drafts/williambsm/tabs
After:
https://milo-section-metadata--blog--webistry-development.hlx.page/en/drafts/williambsm/tabs
I understand it's a slight modification of the block, but I'm hoping that by doing this we will reduce the amount of work required to retroactively fit Milo in the authoring experience and also allow the team to access the capabilities of this block sooner.

Import the Milo Section Metadata block

---

scripts/scripts.js

This is a temporary change (I'll revert after the experiment) that sends
some RUM data to AEP Experience Edge. Normal RUM data will be collected
as usual.
Try it here: https://rum-eedge--blog--adobe.hlx.live/?rum=on

feat(rum): send RUM events to AEP Experience Edge

---

blocks/article-header/article-header.js

- add alt text and aria-label attributes
Test URL: 
https://share-links-missing-alt--blog--adobe.hlx.live/en/publish/2022/10/03/adobe-max-track-be-bold-in-your-drawing-painting-illustration
Pending task:
- update the `{locale}/placeholders.xlsx` for all available regions

MWPW-118278 - Blog posts' share links are missing alt text

---

blocks/marquee/marquee.css
blocks/marquee/marquee.js
styles/styles.css

Migrating the Marquee block over from the Milo main website to Blog.
Milo Marquee demo:
https://milo.adobe.com/docs/library/blocks/marquee
Blog Marquee demo:
https://milo-marquee--blog--webistry-development.hlx.page/en/drafts/williambsm/marquee
There are font sizing differences, but Mat and I agree that until we completely switch to Milo, we should keep the sizing in line with the current Blog sizes.
I have also imported certain functions from the milo script.js and the milo styles.css in order to make this block compatible. If you feel like they should be properly moved to the blog styles.css and script.js let me know, but since this is temporary I felt like we should not pollute the actual blog code until we migrate.
Authoring document: …

Milo marquee

---

tools/sidekick/config.json

When push down is enabled in the sidekick, the `header` remains covered by the sidekick due to its absolute positioning.
To test, enable push down under Options > User Experience and head to
https://main--blog--adobe.hlx.page/
Now change the repository URL to `https://github.com/adobe/blog/tree/sk-push-down-header` under Options > Projects > Blog, then head to:
https://sk-push-down-header--blog--adobe.hlx.page/

chore: push down header when sidekick opens

---

scripts/scripts.js

The way the logic for the Topics pages work is that it would look for any image at all in the original main element on page load, and use it to set it up as a background ([Exibit A](https://main--blog--adobe.hlx.page/en/topics/diverse-voices)). When not using images, it would cause the page to break and align the header in a way that is appropriate ([Exibit B](https://main--blog--adobe.hlx.page/en/topics/digital-transformation)).
The issue with this is that once you are using a block like the Marquee block, the page tries to hijack the Marquee image in order to do its thing ([Exhibit C](https://main--blog--adobe.hlx.page/en/topics/sundance)).
I've built a fix that will allow it to do all of the following three without actually breaking anything in the code.
See Exhibit A, B and C when the …

fix(topics): Fix incompatibility issue with Marquee block

---

blocks/sticky-header/close.svg
blocks/sticky-header/sticky-header.css
blocks/sticky-header/sticky-header.js

Minor list of changes:
- The button is now red
- There is now a close button with the block
- The button should now open in a new tab
Before URL:
https://main--blog--adobe.hlx.page/en/drafts/thomas/sticky-header
After URL:
https://header-open-links--blog--webistry-development.hlx.page/en/drafts/thomas/sticky-header

Requested changes to the Sticky Header block

---

scripts/scripts.js

Read the text below from the previous PR for context: I added some extra checks to make sure it only happens on block-less content. [Exhibit D](https://main--blog--adobe.hlx.page/en/topics/adobe-community-creativity) for the newly broken page.
The way the logic for the Topics pages work is that it would look for any image at all in the original main element on page load, and use it to set it up as a background ([Exibit A](https://main--blog--adobe.hlx.page/en/topics/diverse-voices)). When not using images, it would cause the page to break and align the header in a way that is appropriate ([Exibit B](https://main--blog--adobe.hlx.page/en/topics/digital-transformation)).
The issue with this is that once you are using a block like the Marquee block, the page tries to hijack the Marquee image …

fix(topics): Fix incompatibility issue with Marquee block round 2
